### ISSUE TITLE
Change in physics output with release v.1.1.0

### ISSUE THREAD

**Issue by cipriangal** [JeffersonLab/remoll#44] opened 2017-11-08 18:09 UTC
The physics output after release v.1.1.0 is different from the base v.1.0.0 release and is different from expectations. I attach a couple of plots with direct draws of variables from the output tree for 1000 moller events.

Versions 1.1.1 and 1.1.2 show the exact same behaviour as 1.1.0. 

All these plots are for detector 200, but they will produce similar stuff for detector 28 (the detector we use for background analysis).
**v1.0.0**
![v100](https://user-images.githubusercontent.com/8987591/32566390-c30fcf84-c485-11e7-887a-73ec8af83759.png)
**v1.1.0**
![v110](https://user-images.githubusercontent.com/8987591/32566394-c79a376a-c485-11e7-8b80-b9db92347491.png)

Here are the issues I see:
*The first major issue is that the 7 fold symmetry is somehow broken to 3 fold (see the bottom rows). Selecting electrons (or MOLLER electrons) only does not bring back the 7 fold symmetry. 
*Secondly the number of hits per event increases dramatically from ~10 to 700
*Thirdly the ratio of photons to electrons detected changes (for some reason after v1.1.0 there are many more photons)
*Fourthly with v1.1.0 there seem to be hits at two z positions.
*Lastly the time it takes to run the simulation is significantly increased (I guess this is related to point 2 above since G4 has to process so many more hits). v1.0.0 took ~10 s to run while v1.1.0 took about 230 s.

To reproduce this:
``` 
git clone git@github.com:JeffersonLab/remoll
cd remoll
git checkout -b v1.0.0 v1.0.0
mkdir build;cd build;cmake ../;make;cd -
build/remoll macros/runexample.mac
```
Repeat the last 3 lines for v1.1.0, v1.1.1, v1.1.2

I ran these on the same machine with:
GNU 4.8.5
ROOT 5.34/36
G4.10.2.2

**Comment by cipriangal** [comment] 2017-11-08 18:13
Here is a root script to make the plots I have above:
[drawMoller.txt](https://github.com/JeffersonLab/remoll/files/1454954/drawMoller.txt)

just change the .txt extention to .C

**Comment by wdconinc** [comment] 2017-11-08 18:16
Thanks, will check today.

**Comment by cipriangal** [comment] 2017-11-08 19:43
Found the commit that caused the breaking of the 7 fold symmetry:
https://github.com/JeffersonLab/remoll/commit/e19cfd64c7cff06bf79cb750836e4fbf3ffb4e44#diff-6d3d8081d3407ebac49bf9c9e92a44db

v1.1.0 and making sure we shoot 0,2pi here (https://github.com/JeffersonLab/remoll/blob/master/src/remollGenMoller.cc#L34)
![screen shot 2017-11-08 at 2 38 29 pm](https://user-images.githubusercontent.com/8987591/32570716-fc7525d2-c492-11e7-9e6c-502ddc1e71d3.png)

Since this is probably used in multiple generators without proper initialization I would suggest we change line:
https://github.com/JeffersonLab/remoll/blob/master/src/remollVEventGen.cc#L18
to read fPhi_max(2*CLHEP::pi)

The rest of the stuff remain.

**Comment by wdconinc** [comment] 2017-11-08 19:46
Agreed. I do now remember this issue cropping up. If you commit a fix to develop, I'll merge into master as another bug fix release.

**Comment by wdconinc** [comment] 2017-11-08 19:47
Or I can.

**Comment by wdconinc** [comment] 2017-11-08 19:48
In fact, it's already in develop... https://github.com/JeffersonLab/remoll/blob/develop/src/remollVEventGen.cc#L18

**Comment by wdconinc** [comment] 2017-11-08 19:49
Re, commit a603c5b9e578da828d95c2ce81606b8b5e0dc2e7.

**Comment by wdconinc** [comment] 2017-11-08 20:00
Branch hotfix-issue-44

**Comment by wdconinc** [comment] 2017-11-08 20:12
Still the issue with running much slower. Maybe optical is enabled instead of disabled, as intended.

**Comment by cipriangal** [comment] 2017-11-08 20:26
I think that is related to the increase in number of hits. If I look at it more carefully it does seem like photons in general are increasing (which the electrons seems to remain at about the same level).

**Comment by wdconinc** [comment] 2017-11-08 20:27
It's weird since I have my set of test macros to verify that things are ok, and these test macros generate output that is consistent across versions. May be related to other uninitialized values. Looking into it.

**Comment by wdconinc** [comment] 2017-11-08 23:12
Remaining issue is caused by the test for kryptonite materials in: https://github.com/JeffersonLab/remoll/blob/v1.1.0/src/remollSteppingAction.cc#L42

The list of materials (instead of string comparisons) is initialized in the constructor which is now called before any geometry (and materials) are defined. Therefore kryptonite was effectively turned off... I've committed a new version, 2667c5a.

Three images are:
1. v1.0.0
2. v1.1.0
3. hotfix-issue-44

![image](https://user-images.githubusercontent.com/4656391/32579591-94418b28-c4af-11e7-8829-95161a0b921d.png)
![image](https://user-images.githubusercontent.com/4656391/32579597-9b2903c6-c4af-11e7-9ba1-dd5eac362f5f.png)
![image](https://user-images.githubusercontent.com/4656391/32579614-b6b7b434-c4af-11e7-9159-303c5c564a82.png)

**Closed by wdconinc** 2017-11-08 23:12 UTC
Labels: bug
