### ISSUE TITLE
Macro commands not working, needs documentation for /run/initialize functionality

### ISSUE THREAD

**Issue by cameronc137** [JeffersonLab/remoll#91] opened 2018-06-04 16:24 UTC
When using the "/remoll/evgen/set external" generator the generator's specific macro commands are causing segfaults "***** COMMAND NOT FOUND </remoll/externalfile out/remollout.root> *****"

Also for "/remoll/evgen/external/file out/remollout.root" - It is not clear from the way the remollVEventGenerator, remollPrimaryGeneratorAction, and the individual generator classes are written how these messenger macro commands should be called or where they should be placed relative to /run/initialize.

https://github.com/JeffersonLab/remoll/blob/c26e88903d11fe49553a0f8f7bbae991a4f1c42c/macros/runexample.mac#L49

**Comment by wdconinc** [comment] 2018-06-04 16:44
Only ONE command should ever go before /run/initialize and it's /remoll/setgeofile. Everything else should go after.

But, the problem with the generator commands is a tricky one. You basically have to do
```
/remoll/evgen/set external
/run/beamOn 1
/remoll/evgen/external/file out/remollout.root
```
since the first command actually only gets run when you do /run/beamOn, and only then does it create the third command... It sucks.

**Comment by wdconinc** [comment] 2018-06-04 16:45
Definitely needs more documentation.

**Comment by wdconinc** [comment] 2018-06-04 19:43
How about this? Get rid of /run/initialize completely. Load default geometry that is sensible, do the 'usual' initialization on startup, allow for changing geometry at idle which will force geometry voxelization rebuild, etc.

**Comment by wdconinc** [comment] 2018-06-04 19:43
(doesn't solve issue with lazy loading that causes the command not found errors)

**Comment by wdconinc** [comment] 2018-06-07 15:40
As you may have realized by now, I don't think it's an acceptable solution to add menu/command entries that do not have an effect except when (at some later point) a specific other menu/command entry is given. :-)

**Comment by DanielDeLayo** [comment] 2018-06-07 16:00
Running events after /remoll/evgen/set external doesn't seem to fix the issue of the /remoll/external/file command not found. Could it be that the relevant messengers are thread local (attached to remollVEventGen ) while the macro file is read on the master thread?

**Comment by wdconinc** [comment] 2018-06-07 16:29
Some messengers are per worker thread, others are in the master thread. Geant4 takes care of that by running the master thread ones right away, the worker thread ones at the start of run. That's really at the core of the issue here since this means that `/remoll/evgen/set external` doesn't get run right away. We could move it to a different location, but that will then require writing code to pass info from master thread to worker threads before those worker threads are even created...

But, I'm surprised that running events after `/remoll/evgen/set external` doesn't work for you. Does `macros/tests/unit/test_gen_external.mac` crash for you?

**Comment by wdconinc** [comment] 2018-06-07 16:34
I do see now that `macros/tests/unit/test_gen_external.mac` fails... Not sure since when...

**Comment by wdconinc** [comment] 2018-06-07 16:34
But it doesn't crash due to messenger issues.

**Comment by wdconinc** [comment] 2018-06-07 16:45
Seems like the failing of `remollEvent::IsEventSane()` is caused by the asymmetry being stored and read in ppb which makes them > 1 in abs

**Comment by DanielDeLayo** [comment] 2018-06-07 18:54
Your commit works, thanks.

**Comment by wdconinc** [comment] 2018-07-17 20:30
I think this bug can be closed once branch feature-evgen-hepmc is merged in. That branch does the following:
1. Creates all possible event generators upon startup
2. Creates all associated messenger menu commands upon startup
3. No more errors when calling non-existing menus for inactive generators
4. No more need to run beamOn 1 just to get the menu to show up

I think this is a robust enough solution. Once merged in issue #109 I'll close this here.

**Comment by cameronc137** [comment] 2018-11-19 20:01
@wdconinc is this #109 merge successfully resolving this issue?

**Comment by wdconinc** [comment] 2019-01-08 17:51
Yes, #109 has successfully fixed this. I think having all generators be instantiated was probably the right solution. We may need more docs still, but closing.

**Closed by wdconinc** 2019-01-08 17:51 UTC
