### ISSUE TITLE
Remoll Viewer Crash with Certain Volume is Included

### ISSUE THREAD

**Issue by rakithab** [JeffersonLab/remoll#155] opened 2018-10-10 19:22 UTC
### Environment: (where does this bug occur, have you tried other environments)
- branch (master for latest released): develop
- revision (HEAD for most recent): HEAD
- OS or system: Linux
- Special ROOT or Geant4 versions? geant4-10-03

### Steps to reproduce: (give a step by step account of how to trigger the bug)
1. Include full geometry with all the subsystem into a mollerMother.gdml
2. run the macro in the viewer using /control/execute macros/vis.mac

### Expected Result: (what do you expect when you execute the steps above)
This should generate the geometry in the viewer but remoll crashes if I include Col-1 from the upstream subsystem. 
### Actual Result: (what do you get when you execute the steps above)
remoll crashes with a runtime error

cmd output is shown 

remoll viewer crash when Col-1 is included in the upstream subsystem
```
RunManager construction starting....

*************************************************************
 Geant4 version Name: geant4-10-03    (9-December-2016)
                      Copyright : Geant4 Collaboration
                      Reference : NIM A 506 (2003), 250-303
                            WWW : http://cern.ch/geant4
*************************************************************

remoll: Since the high precision neutron simulation in the default physics list
remoll: generates a lot of warnings that cannot be avoided, we are setting the 
remoll: physics list verbose level to zero. Use /remoll/physlist/verbose to set
remoll: the verbose level to a non-zero value.

You are setting a new verbose level for Particle HP package.
the new value will be used in whole of the Particle HP package, i.e., models and cross sections for Capture, Elastic, Fission and Inelastic interaction.

<<< Geant4 Physics List simulation engine: QGSP_BERT 4.0

<<< Reference Physics List QGSP_BERT is built

remoll: All possible event generators are instantiated every time.
remoll: This means some will not find necessary input files or
remoll: print other information in the next few lines.
Initializing TF1 generator
File name set to remollGenFunctions.root:elastic_0
File name read as remollGenFunctions.root
Function name read as elastic_0
Setting the external file to remollGenFunctions.root
Error in <TFile::TFile>: file remollGenFunctions.root does not exist
could not find function in file remollGenFunctions.root
Constructed remollGenExternal
Setting generator to moller
remoll: Warning: issue 130, double precision input may be truncated.
remoll: see also https://github.com/JeffersonLab/remoll/issues/130
Available UI session types: [ Qt, GAG, tcsh, csh ]

 *** Break *** segmentation violation



===========================================================
There was a crash.
This is the entire stack trace of all threads:
===========================================================

Thread 7 (Thread 0x7f27dc3a8700 (LWP 9372)):
\# pthread_cond_wait

GLIBC_2.3.2 () at ../sysdeps/unix/sysv/linux/x86_64/pthread_cond_wait.S:185
\#  0x00007f27e538a70b in ?? () from /usr/lib/x86_64-linux-gnu/dri/nouveau_dri.so
\#  0x00007f27e538a427 in ?? () from /usr/lib/x86_64-linux-gnu/dri/nouveau_dri.so
\#  0x00007f28168bb6ba in start_thread (arg=0x7f27dc3a8700) at pthread_create.c:333
\#  0x00007f281c76941d in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:109

Thread 6 (Thread 0x7f27fcde2700 (LWP 9370)):
\#  0x00007f281c75f5d3 in select () at ../sysdeps/unix/syscall-template.S:84
\#  0x00007f281493762f in ?? () from /usr/lib/x86_64-linux-gnu/libQtCore.so.4
\#  0x00007f281484ce3c in ?? () from /usr/lib/x86_64-linux-gnu/libQtCore.so.4
\#  0x00007f28168bb6ba in start_thread (arg=0x7f27fcde2700) at pthread_create.c:333
\#  0x00007f281c76941d in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:109

Thread 5 (Thread 0x7f27ef0e4700 (LWP 9366)):
\#  0x00007f281c75d74d in poll () at ../sysdeps/unix/syscall-template.S:84
\#  0x00007f281027438c in ?? () from /lib/x86_64-linux-gnu/libglib-2.0.so.0
\#  0x00007f281027449c in g_main_context_iteration () from /lib/x86_64-linux-gnu/libglib-2.0.so.0
\#  0x00007f281498d2ce in QEventDispatcherGlib::processEvents(QFlags<QEventLoop::ProcessEventsFlag>) () from /usr/lib/x86_64-linux-gnu/libQtCore.so.4
\#  0x00007f281495b18f in QEventLoop::processEvents(QFlags<QEventLoop::ProcessEventsFlag>) () from /usr/lib/x86_64-linux-gnu/libQtCore.so.4
\#  0x00007f281495b4f5 in QEventLoop::exec(QFlags<QEventLoop::ProcessEventsFlag>) () from /usr/lib/x86_64-linux-gnu/libQtCore.so.4
\#  0x00007f281484a549 in QThread::exec() () from /usr/lib/x86_64-linux-gnu/libQtCore.so.4
\#  0x00007f281493b223 in ?? () from /usr/lib/x86_64-linux-gnu/libQtCore.so.4
\#  0x00007f281484ce3c in ?? () from /usr/lib/x86_64-linux-gnu/libQtCore.so.4
\#  0x00007f28168bb6ba in start_thread (arg=0x7f27ef0e4700) at pthread_create.c:333
\# 0x00007f281c76941d in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:109

The lines below might hint at the cause of the crash.
If they do not help you then please submit a bug report at
http://root.cern.ch/bugs. Please post the ENTIRE stack trace
from above as an attachment in addition to anything else
that might help us fixing this issue.
===========================================================
\#  0x00007f2816e03b85 in HepPolyhedron::Transform(HepGeom::Transform3D const&) () from /home/rakithab/softwares/geant4/geant4.10.03-install/lib/libG4graphics_reps.so
\#  0x00007f2817449921 in G4DisplacedSolid::CreatePolyhedron() const () from /home/rakithab/softwares/geant4/geant4.10.03-install/lib/libG4geometry.so
\#  0x00007f2817446964 in G4DisplacedSolid::GetPolyhedron() const () from /home/rakithab/softwares/geant4/geant4.10.03-install/lib/libG4geometry.so
\#  0x00007f28174453f0 in G4BooleanSolid::StackPolyhedron(HepPolyhedronProcessor&, G4VSolid const*) const () from /home/rakithab/softwares/geant4/geant4.10.03-install/lib/libG4geometry.so
\# 0x00007f28174453e0 in G4BooleanSolid::StackPolyhedron(HepPolyhedronProcessor&, G4VSolid const*) const () from /home/rakithab/softwares/geant4/geant4.10.03-install/lib/libG4geometry.so
\# 0x00007f28174453e0 in G4BooleanSolid::StackPolyhedron(HepPolyhedronProcessor&, G4VSolid const*) const () from /home/rakithab/softwares/geant4/geant4.10.03-install/lib/libG4geometry.so
\# 0x00007f28174453e0 in G4BooleanSolid::StackPolyhedron(HepPolyhedronProcessor&, G4VSolid const*) const () from /home/rakithab/softwares/geant4/geant4.10.03-install/lib/libG4geometry.so
\# 0x00007f28174453e0 in G4BooleanSolid::StackPolyhedron(HepPolyhedronProcessor&, G4VSolid const*) const () from /home/rakithab/softwares/geant4/geant4.10.03-install/lib/libG4geometry.so
\# 0x00007f28174453e0 in G4BooleanSolid::StackPolyhedron(HepPolyhedronProcessor&, G4VSolid const*) const () from /home/rakithab/softwares/geant4/geant4.10.03-install/lib/libG4geometry.so
\# 0x00007f28174453e0 in G4BooleanSolid::StackPolyhedron(HepPolyhedronProcessor&, G4VSolid const*) const () from /home/rakithab/softwares/geant4/geant4.10.03-install/lib/libG4geometry.so
\# 0x00007f28174453e0 in G4BooleanSolid::StackPolyhedron(HepPolyhedronProcessor&, G4VSolid const*) const () from /home/rakithab/softwares/geant4/geant4.10.03-install/lib/libG4geometry.so
\# 0x00007f2817453ce4 in G4SubtractionSolid::CreatePolyhedron() const () from /home/rakithab/softwares/geant4/geant4.10.03-install/lib/libG4geometry.so
\# 0x00007f281744400f in G4BooleanSolid::GetPolyhedron() const () from /home/rakithab/softwares/geant4/geant4.10.03-install/lib/libG4geometry.so
\# 0x00007f281ede6042 in G4VSceneHandler::RequestPrimitives(G4VSolid const&) () from /home/rakithab/softwares/geant4/geant4.10.03-install/lib/libG4vis_management.so
\# 0x00007f281eb4baa8 in G4PhysicalVolumeModel::DescribeSolid(HepGeom::Transform3D const&, G4VSolid*, G4VisAttributes const*, G4VGraphicsScene&) () from /home/rakithab/softwares/geant4/geant4.10.03-install/lib/libG4modeling.so
\# 0x00007f281eb4d0ce in G4PhysicalVolumeModel::DescribeAndDescend(G4VPhysicalVolume*, int, G4LogicalVolume*, G4VSolid*, G4Material*, HepGeom::Transform3D const&, G4VGraphicsScene&) () from /home/rakithab/softwares/geant4/geant4.10.03-install/lib/libG4modeling.so
\# 0x00007f281eb4daf4 in G4PhysicalVolumeModel::VisitGeometryAndGetVisReps(G4VPhysicalVolume*, int, HepGeom::Transform3D const&, G4VGraphicsScene&) () from /home/rakithab/softwares/geant4/geant4.10.03-install/lib/libG4modeling.so
\# 0x00007f281eb4d778 in G4PhysicalVolumeModel::DescribeAndDescend(G4VPhysicalVolume*, int, G4LogicalVolume*, G4VSolid*, G4Material*, HepGeom::Transform3D const&, G4VGraphicsScene&) () from /home/rakithab/softwares/geant4/geant4.10.03-install/lib/libG4modeling.so
\# 0x00007f281eb4daf4 in G4PhysicalVolumeModel::VisitGeometryAndGetVisReps(G4VPhysicalVolume*, int, HepGeom::Transform3D const&, G4VGraphicsScene&) () from /home/rakithab/softwares/geant4/geant4.10.03-install/lib/libG4modeling.so
\# 0x00007f281eb4d778 in G4PhysicalVolumeModel::DescribeAndDescend(G4VPhysicalVolume*, int, G4LogicalVolume*, G4VSolid*, G4Material*, HepGeom::Transform3D const&, G4VGraphicsScene&) () from /home/rakithab/softwares/geant4/geant4.10.03-install/lib/libG4modeling.so
\# 0x00007f281eb4daf4 in G4PhysicalVolumeModel::VisitGeometryAndGetVisReps(G4VPhysicalVolume*, int, HepGeom::Transform3D const&, G4VGraphicsScene&) () from /home/rakithab/softwares/geant4/geant4.10.03-install/lib/libG4modeling.so
\# 0x00007f281eb4eda9 in G4PhysicalVolumeModel::DescribeYourselfTo(G4VGraphicsScene&) () fr /home/rakithab/softwares/geant4/geant4.10.03-install/lib/libG4modeling.so
\# 0x00007f281ede68fe in G4VSceneHandler::ProcessScene() () from /home/rakithab/softwares/geant4/geant4.10.03-install/lib/libG4vis_management.so
\# 0x00007f281f0d33c0 in G4OpenGLSceneHandler::ProcessScene() () from /home/rakithab/softwares/geant4/geant4.10.03-install/lib/libG4OpenGL.so
\# 0x00007f281f10a6a0 in G4OpenGLStoredQtViewer::ComputeView() () from /home/rakithab/softwares/geant4/geant4.10.03-install/lib/libG4OpenGL.so
\# 0x00007f281f10a87a in G4OpenGLStoredQtViewer::paintGL() () from /home/rakithab/softwares/geant4/geant4.10.03-install/lib/libG4OpenGL.so
\# 0x00007f28159e62a5 in QGLWidget::glDraw() () from /usr/lib/x86_64-linux-gnu/libQtOpenGL.so.4
\# 0x00007f2814ee08d0 in QWidget::event(QEvent*) () from /usr/lib/x86_64-linux-gnu/libQtGui.so.4
\# 0x00007f28159ef761 in QGLWidget::event(QEvent*) () from /usr/lib/x86_64-linux-gnu/libQtOpenGL.so.4
\# 0x00007f2814e89fdc in QApplicationPrivate::notify_helper(QObject*, QEvent*) () from /usr/lib/x86_64-linux-gnu/libQtGui.so.4
\# 0x00007f2814e90f16 in QApplication::notify(QObject*, QEvent*) () from /usr/lib/x86_64-linux-gnu/libQtGui.so.4
\# 0x00007f281495c90d in QCoreApplication::notifyInternal(QObject*, QEvent*) () from /usr/lib/x86_64-linux-gnu/libQtCore.so.4
\# 0x00007f2814edaf37 in QWidgetPrivate::drawWidget(QPaintDevice*, QRegion const&, QPoint const&, int, QPainter*, QWidgetBackingStore*) () from /usr/lib/x86_64-linux-gnu/libQtGui.so.4
\# 0x00007f28150ad8ad in QWidgetPrivate::repaint_sys(QRegion const&) () from /usr/lib/x86_64-linux-gnu/libQtGui.so.4
\# 0x00007f2814ecdbe7 in QWidgetPrivate::syncBackingStore() () from /usr/lib/x86_64-linux-gnu/libQtGui.so.4
\# 0x00007f2814ee09b8 in QWidget::event(QEvent*) () from /usr/lib/x86_64-linux-gnu/libQtGui.so.4
\# 0x00007f28159ef761 in QGLWidget::event(QEvent*) () from /usr/lib/x86_64-linux-gnu/libQtOpenGL.so.4
\# 0x00007f2814e89fdc in QApplicationPrivate::notify_helper(QObject*, QEvent*) () from /usr/lib/x86_64-linux-gnu/libQtGui.so.4
\# 0x00007f2814e90f16 in QApplication::notify(QObject*, QEvent*) () from /usr/lib/x86_64-linux-gnu/libQtGui.so.4
\# 0x00007f281495c90d in QCoreApplication::notifyInternal(QObject*, QEvent*) () from /usr/lib/x86_64-linux-gnu/libQtCore.so.4
\# 0x00007f28150b1103 in ?? () from /usr/lib/x86_64-linux-gnu/libQtGui.so.4
\# 0x00007f2814ed04b5 in QWidget::repaint(QRect const&) () from /usr/lib/x86_64-linux-gnu/libQtGui.so.4
\# 0x00007f2814ed0513 in QWidget::repaint() () from /usr/lib/x86_64-linux-gnu/libQtGui.so.4
\# 0x00007f281f10a1cc in G4OpenGLStoredQtViewer::DrawView() [clone .localalias.27] () from /home/rakithab/softwares/geant4/geant4.10.03-install/lib/libG4OpenGL.so
\# 0x00007f281ee3323c in G4VisCommandSceneHandlerAttach::SetNewValue(G4UIcommand*, G4String) () from /home/rakithab/softwares/geant4/geant4.10.03-install/lib/libG4vis_management.so
\# 0x00007f281de1f38d in G4UIcommand::DoIt(G4String) () from /home/rakithab/softwares/geant4/geant4.10.03-install/lib/libG4intercoms.so
\# 0x00007f281de3a581 in G4UImanager::ApplyCommand(char const*) () from /home/rakithab/softwares/geant4/geant4.10.03-install/lib/libG4intercoms.so
\# 0x00007f281de0b8c7 in G4UIbatch::ExecCommand(G4String const&) () from /home/rakithab/softwares/geant4/geant4.10.03-install/lib/libG4intercoms.so
\# 0x00007f281de0d69e in G4UIbatch::SessionStart() () from /home/rakithab/softwares/geant4/geant4.10.03-install/lib/libG4intercoms.so
\# 0x00007f281de3b132 in G4UImanager::ExecuteMacroFile(char const*) () from /home/rakithab/softwares/geant4/geant4.10.03-install/lib/libG4intercoms.so
\# 0x00007f281de29261 in G4UIcontrolMessenger::SetNewValue(G4UIcommand*, G4String) () from /home/rakithab/softwares/geant4/geant4.10.03-install/lib/libG4intercoms.so
\# 0x00007f281de1f38d in G4UIcommand::DoIt(G4String) () from /home/rakithab/softwares/geant4/geant4.10.03-install/lib/libG4intercoms.so
\# 0x00007f281de3a581 in G4UImanager::ApplyCommand(char const*) () from /home/rakithab/softwares/geant4/geant4.10.03-install/lib/libG4intercoms.so
\# 0x00007f281de0b8c7 in G4UIbatch::ExecCommand(G4String const&) () from /home/rakithab/softwares/geant4/geant4.10.03-install/lib/libG4intercoms.so
\# 0x00007f281de0d69e in G4UIbatch::SessionStart() () from /home/rakithab/softwares/geant4/geant4.10.03-install/lib/libG4intercoms.so
\# 0x00007f281de3b132 in G4UImanager::ExecuteMacroFile(char const*) () from /home/rakithab/softwares/geant4/geant4.10.03-install/lib/libG4intercoms.so
\# 0x00007f281de29261 in G4UIcontrolMessenger::SetNewValue(G4UIcommand*, G4String) () from /home/rakithab/softwares/geant4/geant4.10.03-install/lib/libG4intercoms.so
\# 0x00007f281de1f38d in G4UIcommand::DoIt(G4String) () from /home/rakithab/softwares/geant4/geant4.10.03-install/lib/libG4intercoms.so
\# 0x00007f281de3a581 in G4UImanager::ApplyCommand(char const*) () from /home/rakithab/softwares/geant4/geant4.10.03-install/lib/libG4intercoms.so
\# 0x00007f281e8bd5bb in G4VBasicShell::ExecuteCommand(G4String const&) () from /home/rakithab/softwares/geant4/geant4.10.03-install/lib/libG4interfaces.so
\# 0x00007f281e8c4bbf in G4VBasicShell::ApplyShellCommand(G4String const&, bool&, bool&) () from /home/rakithab/softwares/geant4/geant4.10.03-install/lib/libG4interfaces.so
\# 0x00007f281e8b1f44 in G4UIQt::CommandEnteredCallback() () from /home/rakithab/softwares/geant4/geant4.10.03-install/lib/libG4interfaces.so
\# 0x00007f2814971010 in QMetaObject::activate(QObject*, QMetaObject const*, int, void**) () from /usr/lib/x86_64-linux-gnu/libQtCore.so.4
\# 0x00007f28152bb975 in ?? () from /usr/lib/x86_64-linux-gnu/libQtGui.so.4
\# 0x00007f2814971010 in QMetaObject::activate(QObject*, QMetaObject const*, int, void**) () from /usr/lib/x86_64-linux-gnu/libQtCore.so.4
\# 0x00007f28152c0b9c in QLineControl::processKeyEvent(QKeyEvent*) () from /usr/lib/x86_64-linux-gnu/libQtGui.so.4
\# 0x00007f28152b5fda in QLineEdit::keyPressEvent(QKeyEvent*) () from /usr/lib/x86_64-linux-gu/libQtGui.so.4
\# 0x00007f2814ee1373 in QWidget::event(QEvent*) () from /usr/lib/x86_64-linux-gnu/libQtGui.so.4
\# 0x00007f28152bba63 in QLineEdit::event(QEvent*) () from /usr/lib/x86_64-linux-gnu/libQtGui.so.4
\# 0x00007f2814e89fdc in QApplicationPrivate::notify_helper(QObject*, QEvent*) () from /usr/lib/x86_64-linux-gnu/libQtGui.so.4
\# 0x00007f2814e92263 in QApplication::notify(QObject*, QEvent*) () from /usr/lib/x86_64-linux-gnu/libQtGui.so.4
\# 0x00007f281495c90d in QCoreApplication::notifyInternal(QObject*, QEvent*) () from /u/lib/x86_64-linux-gnu/libQtCore.so.4
\# 0x00007f2814f346b3 in ?? () from /usr/lib/x86_64-linux-gnu/libQtGui.so.4
\# 0x00007f2814f34bc2 in ?? () from /usr/lib/x86_64-linux-gnu/libQtGui.so.4
\# 0x00007f2814f0cd21 in QApplication::x11ProcessEvent(_XEvent*) () from /usr/lib/x86_64-linux-gnu/libQtGui.so.4
\# 0x00007f2814f37542 in ?? () from /usr/lib/x86_64-linux-gnu/libQtGui.so.4
\# 0x00007f2810274197 in g_main_context_dispatch () from /lib/x86_64-linux-gnu/libglib-2.0.so.0
\# 0x00007f28102743f0 in ?? () from /lib/x86_64-linux-gnu/libglib-2.0.so.0
\# 0x00007f281027449c in g_main_context_iteration () from /lib/x86_64-linux-gnu/libglib-2.0.so.0
\# 0x00007f281498d2ae in QEventDispatcherGlib::processEvents(QFlags<QEventLoop::ProcessEventsFlag>) () from /usr/lib/x86_64-linux-gnu/libQtCore.so.4
\# 0x00007f2814f37616 in ?? () from /usr/lib/x86_64-linux-gnu/libQtGui.so.4
\# 0x00007f281495b18f in QEventLoop::processEvents(QFlags<QEventLoop::ProcessEventsFlag>) () from /usr/lib/x86_64-linux-gnu/libQtCore.so.4
\# 0x00007f281495b4f5 in QEventLoop::exec(QFlags<QEventLoop::ProcessEventsFlag>) () from /usr/lib/x86_64-linux-gnu/libQtCore.so.4
\# 0x00007f28149614b9 in QCoreApplication::exec() () from /usr/lib/x86_64-linux-gnu/libQtCore.so.4
\# 0x00007f281e8acc44 in G4UIQt::SessionStart() () from /home/rakithab/softwares/geant4/geant4.10.03-install/lib/libG4interfaces.so
\# 0x0000000000406548 in main (argc=1, argv=0x7fffd8da8ca8) at /home/rakithab/softwares/MOLLER/remoll_devel/remoll.cc:157
===========================================================


Segmentation fault (core dumped)
```

**Comment by wdconinc** [comment] 2018-10-10 20:59
What do you mean with "Include full geometry with all the subsystem into a mollerMother.gdml"?

Does this issue occur with the mollerMother.gdml or any of the gdml mother files that are included
in the repository? If not, please send me (or attach here) the gdml file that causes the problem.
I can't reproduce this problem.

Other hints:
- use single threaded operation with flag -t 1 and see if that improves things

Also, you can include log output in code blocks using triple backticks (or the <> button on the github issue interface).

**Comment by rakithab** [comment] 2018-12-21 17:20
The viewer crash when I include upstream and downstream daughter volumes. Both volumes contain complicated geometry constructions. When I commented out the above two volumes I can see the geometry in the viewer.  
This issue is machine specific as I see this in certain computers only. So not sure what to say about how to reproduce.

**Comment by wdconinc** [comment] 2018-12-21 21:17
If this is machine specific, please post info on which computers it occurs on and which it doesn't. I am tempted to close this as WONTFIX since we might just be chasing ghosts triggered by bad implementations in older OpenGL versions.

At this point I don't even know (as I asked above) in exactly which geometry this occurs.

**Comment by wdconinc** [comment] 2019-01-11 17:12
Closing since simply not enough info to debug. Please reopen if this still happens and you can provide more info.

**Closed by wdconinc** 2019-01-11 17:12 UTC
