### ISSUE TITLE
Problem of running remoll on ifarm

### ISSUE THREAD

**Issue by chandabindu** [JeffersonLab/remoll#406] opened 2020-11-11 03:06 UTC
Machine: ifarm
Geant4 version: 4.10.06.p02MT
CLHEP 2.4.1.3
ROOT 6.20.04

Branch: develop (fresh copy).
The program complied ( with warning like "make[2]: Warning: File `CMakeFiles/reroot.dir/depend.make' has modification time 0.82 s in the future" and "make[2]: warning:  Clock skew detected.  Your build may be incomplete.")
When I tried to execute the following command "./remoll", the program returned following:
-----
terminate called after throwing an instance of 'std::length_error'
  what():  basic_string::_S_create
Abort
ifarm1801.jlab.org> 
-----------
I tried a fresh copy on desktop (without multi-threading) and that worked.

**Comment by wdconinc** [comment] 2020-11-11 20:01
Which geant4 installation are you using on the farm? There is no 4.10.06.p02MT in any centrally supported location.

**Comment by chandabindu** [comment] 2020-11-11 20:06
Please see email from  Maurizio Ungaro <ungaro@jlab.org>
He has suggested me to use that version:
------
Hello Chandan,

You can use this environment:

https://data.jlab.org/drupal/

to load geant4 10.6 on ifarm1801 or newer.

In particular if you need the multithreaded compiled version of geant4:

setenv GEANT4_VERSION 4.10.06.p02MT
source /site/12gev_phys/softenv.csh 2.4

I’m cc-ing David Lawrence and Thomas Britton as the computer center is taking over the geant4 installation.

Regards,

Mauri

**Comment by wdconinc** [comment] 2020-11-11 23:14
This appears to be caused by using a version of boost compiled against a different version of libstdc++ than the one provided by the compiler. There's not really a solution to this since the problem is with the way softenv.sh sets up its environment, other than the workaround avoiding the offending function (operator/=).

**Comment by chandabindu** [comment] 2020-11-11 23:27
I can compile and run remoll now on ifarm.

**Comment by rahmans1** [comment] 2020-11-12 16:13
I still seem to get this error on ifarm when building.
`[ 96%] Building CXX object CMakeFiles/remoll.dir/remoll.cc.o
[ 98%] Linking CXX executable reroot
libremoll.so: undefined reference to `TString::TString(std::__cxx11::basic_strin              g<char, std::char_traits<char>, std::allocator<char> > const&)'
libremoll.so: undefined reference to `TROOT::RegisterModule(char const*, char co              nst**, char const**, char const*, char const*, void (*)(), std::vector<std::pair              <std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >              , int>, std::allocator<std::pair<std::__cxx11::basic_string<char, std::char_trai              ts<char>, std::allocator<char> >, int> > > const&, char const**, bool)'
collect2: error: ld returned 1 exit status
make[2]: *** [reroot] Error 1
make[1]: *** [CMakeFiles/reroot.dir/all] Error 2
make[1]: *** Waiting for unfinished jobs....
[100%] Linking CXX executable remoll
libremoll.so: undefined reference to `TString::TString(std::__cxx11::basic_strin              g<char, std::char_traits<char>, std::allocator<char> > const&)'
libremoll.so: undefined reference to `TROOT::RegisterModule(char const*, char co              nst**, char const**, char const*, char const*, void (*)(), std::vector<std::pair              <std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >              , int>, std::allocator<std::pair<std::__cxx11::basic_string<char, std::char_trai              ts<char>, std::allocator<char> >, int> > > const&, char const**, bool)'
collect2: error: ld returned 1 exit status
make[2]: *** [remoll] Error 1
make[1]: *** [CMakeFiles/remoll.dir/all] Error 2
make: *** [all] Error 2
`

**Comment by wdconinc** [comment] 2020-11-12 16:16
@rahmans1 That's a different error than this bug report. Please file a new report so I can get info on what geant4 you are using. The error you show is (typically) due to mixing c++11 and c++17 libraries.

**Comment by wdconinc** [comment] 2020-11-12 16:17
I'll close this bug report since @chandabindu has confirmed that is resolved.

**Closed as completed by wdconinc** 2020-11-12 16:17 UTC

**Comment by rahmans1** [comment] 2020-11-12 16:30
Anyways just wanted to confirm that it's resolved. I had to set this environment.
1) module load gcc/9.2.0
2) source /site/12gev_phys/softenv.csh 2.4 
3) source /site/12gev_phys/2.4/Linux_CentOS7.7.1908-gcc9.2.0/root/6.20.04/bin/thisroot.csh
Now it compiles as expected.

**Comment by wdconinc** [comment] 2020-11-12 16:33
I think sourcing thisroot.csh should not be needed as it should be done by softenc.csh. In fact, even module load gcc shouldn't be needed. The only line is the softenv.csh (assuming you start from a relatively clean environment).

**Comment by rahmans1** [comment] 2020-11-12 16:39
@wdconinc You are right. I had a reference to an old root version in my .login script that i put in a few years ago. And it was interfering with the loading of the environment. I just removed it. And just doing `source /site/12gev_phys/softenv.csh 2.4` is indeed sufficient.
